services:
  oracle:
    extends:
      file: deps.yaml
      service: oracle

  keycloak:
    extends:
      file: deps.yaml
      service: keycloak

  dirsrv:
    extends:
      file: deps.yaml
      service: dirsrv

  mailhog:
    extends:
      file: deps.yaml
      service: mailhog

  pam:
    hostname: pam
    container_name: pam
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'pam'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
      KEYCLOAK_FRONTEND_SERVER_URL: 'http://localhost:8081'
      KEYCLOAK_BACKEND_SERVER_URL: 'http://keycloak:8080'
      LOGBOOK_SERVER_URL: 'https://logbooks.jlab.org'
      ORACLE_DATASOURCE: 'pam'
      ORACLE_SERVER: 'oracle:1521'
      ORACLE_USER: 'PAM_OWNER'
      ORACLE_PASS: 'password'
      ORACLE_SERVICE: 'xepdb1'
      BACKEND_SERVER_URL: 'http://pam:8080'
      FRONTEND_SERVER_URL: 'https://localhost:8443'
      TZ: 'America/New_York'
      PAM_FEEDBACK_SENDER_ADDRESS: 'pam@example.com'
      PAM_FEEDBACK_TO_ADDRESS_CSV: 'recipient1@example.com,recipient2@example.com'
      PAM_CONTENT_CONTACT: 'bob@example.com'
      PAM_TECHNICAL_CONTACT: 'larry@example.com'
      PAM_DOC_CSV: 'https://github.com/JeffersonLab/pam|PAM Home'
      LDAP_SERVER_URL: 'ldap://localhost:3389'
      LDAP_USER: 'cn=Directory Manager'
      LDAP_PASS: 'password'
      LDAP_USER_SUFFIX: 'cn=users,cn=accounts,dc=example,dc=com'
      LDAP_GROUP_SUFFIX: 'cn=groups,cn=accounts,dc=example,dc=com'
      LDAP_OPS_MANAGED_CN: 'opsmngd'