# Note: Windows users must enable systemd support: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#systemd-support
services:
  ipa:
    image: freeipa/freeipa-server:rocky-9-4.10.2
    hostname: ipa.example.com
    container_name: ipa
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      PASSWORD: password
      IPA_SERVER_INSTALL_OPTS: '-r EXAMPLE.COM -N -U'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
